baseurl = "/"
languageCode = "pt-br"
title = "PiXeLaDaS "
theme = ["hugo-atom-feed", "hugo-theme-casper"]
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/botbot.jpg"
  author = ""
  authorlocation = "Em algum local da galáxia"
  authorwebsite = ""
  bio= ""
  logo = "images/bots.jpg"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = ""
  twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = ""
    
 [outputs]
  # <domain>/atom.xml
  home = ["HTML", "RSS", "ATOM"]     # default = ["HTML", "RSS"]
  # <domain>/posts/atom.xml
  section = ["HTML", "RSS", "ATOM"]  # default = ["HTML", "RSS"]
  # <domain>/tags/mytag/atom.xml, <domain>/categories/mycat/atom.xml
  taxonomy = ["HTML", "RSS", "ATOM"] # default = ["HTML", "RSS"]
    
    
   # Atom feed
# Add "ATOM" to the Page Kinds under [outputs] (in your site config) for which
# you want to enable Atom feeds.
# Example:
#   [outputs]
#     home = ["HTML", "ATOM"]
# https://gist.github.com/lpar/7ded35d8f52fef7490a5be92e6cd6937
[mediaTypes]
[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]
[outputFormats.Atom]
  # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "atom" # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
  isPlainText = false
  rel = "alternate"
  isHTML = false
  noUgly = true
  permalinkable = false 
 
