baseurl = "https://www.pixeladasx.com/"
defaultContentLanguage = "en"
languageCode = "en-us"
languageLang = "pt"
title = "PiXeLaDaS "
theme = "hugo-theme-casper"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "Seu espaço de entretenimento digital"
  cover = "images/duplicabot.jpg"
  author = "pixeladasx"
  authorlocation = "Em algum local da galáxia"
  bio= "Master of Illusion"
  logo = "images/bots.jpg"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "https://pixeladasx.us19.list-manage.com/subscribe/post?u=a6f2cac71996cb3b7aba9a34c&amp;id=76ccc40c89"
  githubName = ""
  twitterName = ""
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  
  [params.social]
    twitter = ""
    
 


    

